### ISSUE TITLE
Consider adding gia to bioconda?

### ISSUE THREAD

**Issue by mrvollger** [noamteyssier/gia#117]
Hi @noamteyssier,

I have been enjoying using gia! Any plans to add it to bioconda? I use it in several pipelines and conda is helpful in solving dependencies a little easier. 

Cheers,
Mitchell

**Comment by noamteyssier** [comment]
Hey Mitchell,

I'm glad you've been using it! I haven't really considered it since I don't use conda much. But If you think that this would make it easier to use and distribute I wouldn't mind looking into that.

**Comment by mrvollger** [comment]
Hi @noamteyssier,

I have built the bioconda recipe, and I am working on getting it to build, which I don't think will be too hard. 
https://github.com/bioconda/bioconda-recipes/pull/49361

In the future bioconda should be able to automatically make PRs for new releases as long as the releases have tags with the format X.X.X where X is a number.

Specifically, it is checking for URLs at:
```
https://github.com/noamteyssier/gia/archive/{{ version }}.tar.gz
```
which should be autogenerated on releases. 

Cheers,
Mitchell

PS If merged, the version reported on bioconda will be 0.2 and not 0.2.20 because the tag for the release of 0.2.20 was 0.2 and not 0.2.20.

**Comment by mrvollger** [comment]
Merged into bioconda. Feel free to close.

**Comment by noamteyssier** [comment]
Hey Mitchell,

Thanks so much for doing this!
I appreciate you taking the initiative to set it up on bioconda. 

Cheers,
Noam

**Comment by mrvollger** [comment]
Of course (I did it for myself). 

I saw with your recent release, you used the tag v0.2.23, which wasn't detected by bioconda because I set it up to look for X.X.X vs **v**X.X.X (because it was just 0.2 in the previous release). 

I can set it up, either way, going forward, but it would be nice to keep a consistent format for the release tag so that bioconda will find it without me needing to open PRs. 

Do you know if you intend to use X.X.X or vX.X.X going forward?

**Comment by noamteyssier** [comment]
Ah okay, I think let’s use the x.x.x style and I’ll just re release it without the v.

**Comment by mrvollger** [comment]
awesome, thanks!
