### ISSUE TITLE
bed12 support, -wo flag support

### ISSUE THREAD

**Issue by ddubocan** [noamteyssier/gia#50]
Thanks so much for providing this tool to the community! I am finding it much faster than the existing toolkits.
Would it be possible to provide support for the bed12 format? Additionally, would it be possible to extend functionality to additional bedtools intersect flags such as -wo?
For people working in the single-molecule sequencing space these additions would be massively helpful.

Thanks again!

**Comment by noamteyssier** [comment]
Thanks for submitting the request, glad to hear it's been working for you!

 definitely possible to support BED12 - you can follow the progress of that in #53 

I can also implement the `-wo` flag and you can follow that progress in #52

**Comment by noamteyssier** [comment]
This as been added in #112
