### ISSUE TITLE
Add support for compressed files

### ISSUE THREAD

**Issue by mrvollger** [noamteyssier/gia#56]
Hi @noamteyssier,

This seems like a great potential tool, but my bed files tend to be very large, so it would be awesome if you would considered allowing for compressed input (maybe through https://github.com/luizirber/niffler) and multithreaded compression of the output (maybe through https://github.com/sstadick/gzp). 

Thanks for considering!
Mitchell

**Comment by mrvollger** [comment]
If it is helpful, I have examples of reading compressed input:
https://github.com/fiberseq/fibertools-rs/blob/ea456be994b9209e32332bf5b46c183eba45ca3d/bio-io/src/lib.rs#L93-L117
and writing compressed output:
https://github.com/fiberseq/fibertools-rs/blob/ea456be994b9209e32332bf5b46c183eba45ca3d/bio-io/src/lib.rs#L48-L79
with these tools. However, my rust skills are still quite poor, so they may not be the best template to work from.

Oh also, for the compressed output I use bgzip, which if sorted, allows for indexing with tools like `tabix`, so that might be worth considering.

**Comment by noamteyssier** [comment]
Thanks for the suggestions! I agree this would be a great addition to the tool. 

I think it could be a pretty quick thing to add - would probably add it to my existing `match_input` function:
https://github.com/noamteyssier/gia/blob/0d3f9fe584aa865b7efbe60ca4256a518b4c31a5/src/io/general.rs#L7-L21

and to the converse `match_output` function:
https://github.com/noamteyssier/gia/blob/0d3f9fe584aa865b7efbe60ca4256a518b4c31a5/src/io/general.rs#L23-L36

**Comment by mrvollger** [comment]
@noamteyssier great to hear! If you would like I could start a PR for this since you have pointed me in the right direction?

**Comment by noamteyssier** [comment]
That sounds great to me if you'd like to give it a shot

**Comment by noamteyssier** [comment]
supported with #59 

Thanks for the PR and the suggestion!
