### ISSUE TITLE
Retain BED6 format?

### ISSUE THREAD

**Issue by aseveritt** [noamteyssier/gia#65]
Hi Noam! 

I'm running a lot of bedtools intersect commands that I would love to replace with gia, but I was relying on the information in the bed6 format being retained. 

e.g. fileA.bed
chr1	29300	29400

e.g. fileB.bed
chr1	29301	29400	CTAACTTTCCTATCAT-1	41	+
chr1	29328	29427	CTAACTTTCCTATCAT-1	40	-

e.g. output I need with the cell barcode. 
chr1	29301	29400	CTAACTTTCCTATCAT-1	41	+

In this case, would I need to use bedrs instead of gia & create an interval type with my additional field?
-- Amanda

**Comment by aseveritt** [comment]
Ah, sorry just saw issue #50 and #53. I assume that would solve this question too.

**Comment by noamteyssier** [comment]
Hey Amanda,

This is actually a different issue of mixing file formats (in this case bed3 and bed6). It's on my docket but I haven't had time to work on it yet.

A hacky workaround that you can use to use it immediately is to just make a pseudo bed6 from your bed3:

```bash
awk 'OFS="\t"{print $1, $2, $3, 0, 0, "+"}' < fileA.bed > fileA.bed6 
```

and then to process the bed files with the bed6 input format (the `-T` flag) you can run:

```bash
gia intersect -a fileA.bed6 -b fileB.bed -T bed6
```

Hopefully that should work for your use case. 

It adds an extra step which is kind of annoying but my plan is to have both the inter-format comparisons built and auto-determining input format built after Thanksgiving.

**Comment by aseveritt** [comment]
Thank you!! That workaround totally works for me.

**Comment by noamteyssier** [comment]
This took way longer than I wanted but this functionality has been added without the workaround in #112
